import { defineToolcraft, imageExportModule } from "@/toolcraft/runtime";

import appDefaults from "./app-defaults.json" with { type: "json" };
import { appIdentity } from "./app-identity";

export const appSchema = defineToolcraft({
  defaults: appDefaults,
  base: {
    canvas: {
      enabled: true,
      sizing: { mode: "editable-output" },
    },
    identity: appIdentity,
    panels: {
      controls: {
        sections: [
          {
            id: "background",
            controls: {
              includeBackground: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "Include",
                performanceReason:
                  "Toggles background rendering in raster output and export",
                performanceRole: "responsiveness",
                target: "export.includeBackground",
                type: "switch",
              },
              background: {
                applicability: { mode: "always" },
                defaultValue: "#0D1117",
                label: false,
                performanceReason:
                  "Background color fill in raster output and export",
                performanceRole: "responsiveness",
                target: "appearance.background",
                type: "color",
              },
            },
            title: "Background",
          },
          {
            id: "circles",
            controls: {
              strokeWidth: {
                applicability: { mode: "always" },
                defaultValue: 3,
                label: "Circle thickness",
                max: 20,
                min: 1,
                performanceReason:
                  "Controls rasterization thickness of circle borders",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 1,
                target: "circles.strokeWidth",
                type: "slider",
                unit: "px",
              },
              fillOpacity: {
                applicability: { mode: "always" },
                defaultValue: 0.15,
                label: "Fill opacity",
                max: 1,
                min: 0,
                performanceReason: "Controls transparency of circle interiors",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 0.05,
                target: "circles.fillOpacity",
                type: "slider",
              },
              color1: {
                applicability: { mode: "always" },
                defaultValue: "#38BDF8",
                label: "Circle A",
                performanceReason: "Circle A accent color",
                performanceRole: "responsiveness",
                semanticGroup: "circle-palette",
                target: "circles.color1",
                type: "color",
              },
              color2: {
                applicability: { mode: "always" },
                defaultValue: "#C084FC",
                label: "Circle B",
                performanceReason: "Circle B accent color",
                performanceRole: "responsiveness",
                semanticGroup: "circle-palette",
                target: "circles.color2",
                type: "color",
              },
              color3: {
                applicability: { mode: "always" },
                defaultValue: "#FB7185",
                label: "Circle C",
                performanceReason: "Circle C accent color",
                performanceRole: "responsiveness",
                semanticGroup: "circle-palette",
                target: "circles.color3",
                type: "color",
              },
              radius1: {
                applicability: { mode: "always" },
                defaultValue: 110,
                label: "Radius A",
                max: 250,
                min: 20,
                performanceReason: "Radius of circle A",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 1,
                target: "circles.radius1",
                type: "slider",
                unit: "px",
              },
              radius2: {
                applicability: { mode: "always" },
                defaultValue: 70,
                label: "Radius B",
                max: 250,
                min: 20,
                performanceReason: "Radius of circle B",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 1,
                target: "circles.radius2",
                type: "slider",
                unit: "px",
              },
              radius3: {
                applicability: { mode: "always" },
                defaultValue: 42,
                label: "Radius C",
                max: 250,
                min: 20,
                performanceReason: "Radius of circle C",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 1,
                target: "circles.radius3",
                type: "slider",
                unit: "px",
              },
            },
            title: "Circles",
          },
          {
            id: "geometry",
            controls: {
              distanceScale: {
                applicability: { mode: "always" },
                defaultValue: 1.0,
                label: "Distance scale",
                max: 2.5,
                min: 0.5,
                performanceReason:
                  "Controls spatial spread between circle centers",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 0.05,
                target: "geometry.distanceScale",
                type: "slider",
              },
              layoutPreset: {
                applicability: { mode: "always" },
                defaultValue: "triangle",
                label: "Preset",
                options: [
                  { label: "Triangle", value: "triangle" },
                  { label: "Ascending", value: "ascending" },
                  { label: "Offset", value: "offset" },
                ],
                performanceReason:
                  "Changes geometric layout distribution of circles",
                performanceRole: "responsiveness",
                target: "geometry.layoutPreset",
                type: "select",
              },
            },
            title: "Geometry",
          },
          {
            id: "lines",
            controls: {
              tangentStrokeWidth: {
                applicability: { mode: "always" },
                defaultValue: 2,
                label: "Tangent thickness",
                max: 15,
                min: 1,
                performanceReason:
                  "Controls line thickness of external common tangents",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 0.5,
                target: "lines.tangentStrokeWidth",
                type: "slider",
                unit: "px",
              },
              mongeLineStrokeWidth: {
                applicability: { mode: "always" },
                defaultValue: 3.5,
                label: "Monge line thickness",
                max: 15,
                min: 1,
                performanceReason:
                  "Controls stroke thickness of Monge's collinear line",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 0.5,
                target: "lines.mongeLineStrokeWidth",
                type: "slider",
                unit: "px",
              },
              tangentColor: {
                applicability: { mode: "always" },
                defaultValue: "#94A3B8",
                label: "Tangent color",
                performanceReason: "Color of tangent lines",
                performanceRole: "responsiveness",
                semanticGroup: "line-palette",
                target: "lines.tangentColor",
                type: "color",
              },
              mongeLineColor: {
                applicability: { mode: "always" },
                defaultValue: "#F59E0B",
                label: "Monge line color",
                performanceReason:
                  "Color of Monge's theorem collinear line",
                performanceRole: "responsiveness",
                semanticGroup: "line-palette",
                target: "lines.mongeLineColor",
                type: "color",
              },
              showMongeLine: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "Monge line",
                performanceReason:
                  "Toggles visibility of the Monge collinear line",
                performanceRole: "responsiveness",
                target: "lines.showMongeLine",
                type: "switch",
              },
              showExternalTangents: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "External tangents",
                performanceReason:
                  "Toggles visibility of external common bitangents",
                performanceRole: "responsiveness",
                target: "lines.showExternalTangents",
                type: "switch",
              },
              showInternalTangents: {
                applicability: { mode: "always" },
                defaultValue: false,
                label: "Internal tangents",
                performanceReason:
                  "Toggles internal tangents (Desargues configuration)",
                performanceRole: "responsiveness",
                target: "lines.showInternalTangents",
                type: "switch",
              },
              showCenterLines: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "Center lines",
                performanceReason:
                  "Toggles dashed lines connecting circle centers",
                performanceRole: "responsiveness",
                target: "lines.showCenterLines",
                type: "switch",
              },
            },
            title: "Lines",
          },
          {
            id: "annotations",
            controls: {
              showLabels: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "Labels",
                performanceReason: "Toggles circle and point labels",
                performanceRole: "responsiveness",
                target: "annotations.showLabels",
                type: "switch",
              },
              showPoints: {
                applicability: { mode: "always" },
                defaultValue: true,
                label: "Points",
                performanceReason:
                  "Toggles center and intersection points",
                performanceRole: "responsiveness",
                target: "annotations.showPoints",
                type: "switch",
              },
              fontSize: {
                applicability: { mode: "always" },
                defaultValue: 16,
                label: "Font size",
                max: 32,
                min: 12,
                performanceReason: "Controls text size of labels",
                performanceRole: "responsiveness",
                sliderValueKind: "continuous",
                step: 1,
                target: "annotations.fontSize",
                type: "slider",
                unit: "px",
              },
              labelColor: {
                applicability: { mode: "always" },
                defaultValue: "#F8FAFC",
                label: "Label color",
                performanceReason: "Color of text labels",
                performanceRole: "responsiveness",
                semanticGroup: "annotation-palette",
                target: "annotations.labelColor",
                type: "color",
              },
            },
            layoutGroups: [
              {
                columns: 2,
                controls: ["showLabels", "showPoints"],
                layout: "inline",
              },
            ],
            title: "Annotations",
          },
        ],
        title: "Controls",
      },
    },
    toolbar: {
      history: true,
      radar: true,
      zoom: true,
    },
  },
  modules: [imageExportModule()],
});
