import type { ToolcraftComponentAcceptance } from "./acceptance/types";
import { appSchema } from "./app-schema";

const starterPersistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName:
      "declares production reload coverage for the product schema",
    browser: {
      budget: "extended-io",
      file: "e2e/app-persistence.spec.ts",
      testName:
        "browser: app restores exact canvas, values, and panel workspace slices after reload",
    },
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, diagram values, and Controls panel workspace remain visibly restored after a real browser reload.",
    fixture: "monge persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices: starterPersistenceSlices,
    target: "canvas.size.width",
    userAction:
      "Edit Canvas width and circle thickness, move Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName:
      "background inclusion controls preview and PNG transparency",
    backgroundOutputCoverage: [
      "preview-hidden-when-excluded",
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
    ],
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: background inclusion controls output",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Turning Background off removes the canvas preview base, exports transparent PNG corners, and disables Infinity canvas.",
    fixture: "monge background inclusion",
    id: "renderer.background-inclusion",
    kind: "control",
    target: "export.includeBackground",
    userAction:
      "Toggle Background switch and observe canvas preview and PNG transparency.",
  },
  {
    automated: true,
    automatedTestName: "background color changes diagram export output",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: background color reaches export",
    },
    componentType: "color",
    evidence: "exported-bytes",
    expectedObservable:
      "The selected Background color appears in the canvas and exported image background.",
    fixture: "monge background color",
    id: "renderer.background-color",
    kind: "control",
    target: "appearance.background",
    userAction:
      "Change Background color and verify the new background color in export.",
  },
  {
    automated: true,
    automatedTestName: "circle thickness slider adjusts circle borders",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: circle thickness adjusts borders",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Circle thickness widens or narrows the rendered border of the circles.",
    fixture: "monge circle thickness",
    id: "control.circles.stroke-width",
    interactionId: "circle-stroke-width",
    kind: "control",
    target: "circles.strokeWidth",
    userAction: "Drag Circle thickness slider to change stroke width.",
  },
  {
    automated: true,
    automatedTestName: "circle fill opacity slider adjusts transparency",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: circle fill opacity adjusts transparency",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Fill opacity changes transparency of the circle discs.",
    fixture: "monge circle fill opacity",
    id: "control.circles.fill-opacity",
    kind: "control",
    target: "circles.fillOpacity",
    userAction: "Drag Fill opacity slider to change interior transparency.",
  },
  {
    automated: true,
    automatedTestName: "circle A color adjusts first circle color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: circle A color changes circle A",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Circle A updates Circle A border and fill tint.",
    fixture: "monge circle A color",
    id: "control.circles.color1",
    interactionId: "circle-color-1",
    kind: "control",
    target: "circles.color1",
    userAction: "Select a color for Circle A.",
  },
  {
    automated: true,
    automatedTestName: "circle B color adjusts second circle color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: circle B color changes circle B",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Circle B updates Circle B border and fill tint.",
    fixture: "monge circle B color",
    id: "control.circles.color2",
    kind: "control",
    target: "circles.color2",
    userAction: "Select a color for Circle B.",
  },
  {
    automated: true,
    automatedTestName: "circle C color adjusts third circle color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: circle C color changes circle C",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Circle C updates Circle C border and fill tint.",
    fixture: "monge circle C color",
    id: "control.circles.color3",
    kind: "control",
    target: "circles.color3",
    userAction: "Select a color for Circle C.",
  },
  {
    automated: true,
    automatedTestName: "radius A slider updates first circle radius",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: radius A slider scales circle A",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Radius A scales circle A and dynamically recomputes common tangents.",
    fixture: "monge radius A",
    id: "control.circles.radius1",
    kind: "control",
    target: "circles.radius1",
    userAction: "Drag Radius A slider to adjust the first circle radius.",
  },
  {
    automated: true,
    automatedTestName: "radius B slider updates second circle radius",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: radius B slider scales circle B",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Radius B scales circle B and dynamically recomputes common tangents.",
    fixture: "monge radius B",
    id: "control.circles.radius2",
    kind: "control",
    target: "circles.radius2",
    userAction: "Drag Radius B slider to adjust the second circle radius.",
  },
  {
    automated: true,
    automatedTestName: "radius C slider updates third circle radius",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: radius C slider scales circle C",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Radius C scales circle C and dynamically recomputes common tangents.",
    fixture: "monge radius C",
    id: "control.circles.radius3",
    kind: "control",
    target: "circles.radius3",
    userAction: "Drag Radius C slider to adjust the third circle radius.",
  },
  {
    automated: true,
    automatedTestName: "distance scale slider scales distance between circles",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: distance scale changes circle separation",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Distance scale spreads or contracts circle centers while preserving collinear Monge alignment.",
    fixture: "monge distance scale",
    id: "control.geometry.distance-scale",
    interactionId: "distance-scale",
    kind: "control",
    target: "geometry.distanceScale",
    userAction: "Drag Distance scale slider to spread circle centers.",
  },
  {
    automated: true,
    automatedTestName: "preset selector switches geometry arrangement",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: preset switches geometry arrangement",
    },
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Switching between Triangle, Ascending, and Offset presets reorganizes circle centers.",
    fixture: "monge layout preset",
    id: "control.geometry.layout-preset",
    kind: "control",
    optionCoverage: ["triangle", "ascending", "offset"],
    target: "geometry.layoutPreset",
    userAction: "Select Triangle, Ascending, and Offset presets.",
  },
  {
    automated: true,
    automatedTestName: "tangent thickness slider adjusts tangent line width",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: tangent thickness adjusts line width",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Tangent thickness widens or narrows rendered common tangent lines.",
    fixture: "monge tangent thickness",
    id: "control.lines.tangent-stroke-width",
    interactionId: "tangent-stroke-width",
    kind: "control",
    target: "lines.tangentStrokeWidth",
    userAction: "Drag Tangent thickness slider to adjust line width.",
  },
  {
    automated: true,
    automatedTestName:
      "monge line thickness slider adjusts collinear line width",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: monge line thickness adjusts line width",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Monge line thickness widens or narrows the collinear theorem line.",
    fixture: "monge line thickness",
    id: "control.lines.monge-line-stroke-width",
    kind: "control",
    target: "lines.mongeLineStrokeWidth",
    userAction: "Drag Monge line thickness slider to adjust stroke width.",
  },
  {
    automated: true,
    automatedTestName: "tangent color picker adjusts tangent lines color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: tangent color updates tangent lines",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Tangent color updates the stroke color of external tangent lines.",
    fixture: "monge tangent color",
    id: "control.lines.tangent-color",
    interactionId: "tangent-color",
    kind: "control",
    target: "lines.tangentColor",
    userAction: "Pick a color for Tangent color.",
  },
  {
    automated: true,
    automatedTestName: "monge line color picker adjusts collinear line color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: monge line color updates collinear line",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Monge line color updates the stroke and glow color of the collinear line.",
    fixture: "monge line color",
    id: "control.lines.monge-line-color",
    kind: "control",
    target: "lines.mongeLineColor",
    userAction: "Pick a color for Monge line color.",
  },
  {
    automated: true,
    automatedTestName: "glow slider adjusts halo radius for lines and circles",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: glow slider adjusts halo radius",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Glow slider expands or contracts the radiant bloom around circles, tangents, and theorem lines.",
    fixture: "monge glow intensity",
    id: "control.lines.glow-intensity",
    interactionId: "glow-intensity",
    kind: "control",
    target: "lines.glowIntensity",
    userAction: "Drag Glow slider to adjust shadow blur radius.",
  },
  {
    automated: true,
    automatedTestName: "monge line switch toggles collinear line visibility",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: monge line switch toggles visibility",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Monge line switch shows or hides Monge's theorem collinear line.",
    fixture: "monge line toggle",
    id: "control.lines.show-monge-line",
    kind: "control",
    target: "lines.showMongeLine",
    userAction: "Toggle Monge line switch.",
  },
  {
    automated: true,
    automatedTestName:
      "external tangents switch toggles tangent line visibility",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: external tangents switch toggles lines",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling External tangents switch shows or hides external common bitangent lines.",
    fixture: "external tangents toggle",
    id: "control.lines.show-external-tangents",
    kind: "control",
    target: "lines.showExternalTangents",
    userAction: "Toggle External tangents switch.",
  },
  {
    automated: true,
    automatedTestName:
      "internal tangents switch toggles internal tangent visibility",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: internal tangents switch toggles lines",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Internal tangents switch shows or hides internal common tangents.",
    fixture: "internal tangents toggle",
    id: "control.lines.show-internal-tangents",
    kind: "control",
    target: "lines.showInternalTangents",
    userAction: "Toggle Internal tangents switch.",
  },
  {
    automated: true,
    automatedTestName: "center lines switch toggles center connection lines",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: center lines switch toggles dashed lines",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Center lines switch shows or hides the dashed lines connecting circle centers.",
    fixture: "center lines toggle",
    id: "control.lines.show-center-lines",
    kind: "control",
    target: "lines.showCenterLines",
    userAction: "Toggle Center lines switch.",
  },
  {
    automated: true,
    automatedTestName: "labels switch toggles circle and point text labels",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: labels switch toggles text labels",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Labels switch shows or hides text badges for circles and points.",
    fixture: "monge labels toggle",
    id: "control.annotations.show-labels",
    kind: "control",
    target: "annotations.showLabels",
    userAction: "Toggle Labels switch.",
  },
  {
    automated: true,
    automatedTestName: "points switch toggles center and intersection markers",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: points switch toggles indicator dots",
    },
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Points switch shows or hides center and homothetic center indicator dots.",
    fixture: "monge points toggle",
    id: "control.annotations.show-points",
    kind: "control",
    target: "annotations.showPoints",
    userAction: "Toggle Points switch.",
  },
  {
    automated: true,
    automatedTestName: "font size slider adjusts label font size",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: font size slider changes label scale",
    },
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Adjusting Font size changes the rendered typography size of diagram labels.",
    fixture: "monge font size",
    id: "control.annotations.font-size",
    kind: "control",
    target: "annotations.fontSize",
    userAction: "Drag Font size slider to adjust label text size.",
  },
  {
    automated: true,
    automatedTestName: "label color picker adjusts label text color",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: label color updates label text",
    },
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Selecting a color for Label color updates the text fill of diagram labels.",
    fixture: "monge label color",
    id: "control.annotations.label-color",
    kind: "control",
    target: "annotations.labelColor",
    userAction: "Pick a color for Label color.",
  },
  {
    automated: true,
    automatedTestName: "image format options remain selectable",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: image formats remain selectable",
    },
    componentType: "select",
    evidence: "product-output",
    expectedObservable: "PNG and JPG remain available image formats.",
    fixture: "monge image formats",
    id: "export.image.format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select PNG and JPG and observe the selected format.",
  },
  {
    automated: true,
    automatedTestName: "image resolution options remain selectable",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: image resolutions remain selectable",
    },
    componentType: "select",
    evidence: "product-output",
    expectedObservable: "2K, 4K, and 8K remain available image resolutions.",
    fixture: "monge image resolutions",
    id: "export.image.resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select 2K, 4K, and 8K and observe the selected resolution.",
  },
  {
    actionCoverage: ["export.png"],
    automated: true,
    automatedTestName: "monge theorem 4K image export is deterministic",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: image export uses scene bounds",
    },
    componentType: "panelActions",
    evidence: "exported-bytes",
    exportArtifactCoverage: "all-required-image-export-behavior",
    expectedObservable:
      "PNG export renders at requested resolution and contains the complete Monge circle theorem diagram.",
    fixture: "monge scene-bounds image export",
    id: "renderer.image-export",
    kind: "control",
    target: "actions.output",
    userAction: "Export PNG and inspect decoded image dimensions and content.",
  },
  {
    automated: true,
    automatedTestName:
      "monge diagram uses runtime scene bounds across Infinity",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: Infinity scene bounds",
    },
    componentType: "canvas",
    evidence: "viewport-side-effect",
    expectedObservable:
      "Infinity mode changes only the finite boundary while the Monge diagram world frame and canvas backing remain continuous.",
    fixture: "infinite monge bounds",
    id: "renderer.infinity-mode",
    infinityCanvasCoverage: "mode-continuity-and-restoration",
    kind: "runtime",
    target: "canvas.infinity",
    userAction:
      "Toggle Infinity both directions and inspect diagram frame and backing continuity.",
  },
  {
    automated: true,
    automatedTestName: "monge export preserves framing across Infinity",
    browser: {
      budget: "standard",
      file: "e2e/app-browser-acceptance.spec.ts",
      testName: "browser acceptance: export preserves framing across Infinity",
    },
    componentType: "canvas",
    evidence: "exported-bytes",
    expectedObservable:
      "Infinity PNG export preserves the saved finite artboard dimensions, crop, background and decoded pixels.",
    fixture: "monge scene-bounds image crop",
    id: "renderer.infinity-export",
    infinityCanvasCoverage: "scene-bounds-image-export",
    kind: "runtime",
    target: "canvas.infinity",
    userAction:
      "Enable Infinity canvas, export PNG, and verify decoded image bounds and pixels.",
  },
];
